[features]
seeds = false
skip-lint = false
[programs.localnet]
wba_vault = "Gss8LX9bLNVB9e37eUrtqouWMGeuqNTUyJEhCkYZNhVK"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Localnet"
wallet = "/home/jrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
